project_id: "9"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
"base_url": "https://meshtastic.crowdin.com"
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # Pages Markdown files
  - source: /pages/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
