// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  Sidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "link",
      label: "Glossary of Terms",
      href: "/docs/terms/",
    },
  ],
};
