// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  Sidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  developers: [
    {
      type: 'category',
      label: 'Developers',
      link: {
        type: 'generated-index',
        title: 'Developer Documentation',
        description: 'Meshtastic developer resources',
        slug: '/developers',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers',
        },
      ],
    },
  ],
};
