// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  Sidebar: [
    {
      type: "autogenerated",
      dirName: "."
    },
    {
      type: "category",
      label: "Development",
      items: [
        {
          type: "autogenerated",
          dirName: "development"
        },
        {
          type: "category",
          label: "Reference Material",
          items: [
            {
              type: "autogenerated",
              dirName: "development/reference"
            },
            {
              type: "link",
              label: "Protobuf Docs",
              href: "https://buf.build/meshtastic/protobufs"
            }
          ]
        }
      ]
    }
  ]
};
