name: Crowdin

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_sources_args: "--delete-obsolete"
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_master
          create_pull_request: true
          pull_request_title: "chore(i18n): new Crowdin translations"
          pull_request_body: "New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)"
          pull_request_base_branch_name: master
          config: crowdin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
